"""Type II (closed model) multipliers — households endogenous.

Extends the Leontief model by adding household consumption and income
as an endogenous sector. Type II multipliers capture induced effects
(consumer spending from wage income) in addition to direct + indirect.

Ā = [[A,  hc],    where hc = household consumption pattern
     [hr,  0 ]]         hr = labor income coefficients

Reference: Miller & Blair (2009), Ch. 2 — from Wynne KB.
"""

import numpy as np
import pandas as pd
from scipy import linalg
import logging

logger = logging.getLogger(__name__)


def close_model(
    A: pd.DataFrame,
    use_table: pd.DataFrame,
    value_added: pd.DataFrame,
    final_demand: pd.DataFrame,
    total_output: pd.Series,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Build closed (Type II) A-bar matrix with households endogenous.

    Args:
        A: Direct requirements matrix (n x n).
        use_table: Full Use table (for extracting PCE column).
        value_added: VA components (for compensation row).
        final_demand: FD categories (for PCE column).
        total_output: Total industry output.

    Returns:
        (A_bar, L_bar) — extended matrices with household row/col.
    """
    # Use L_matrix sectors if A is non-square; otherwise use A's index
    # A can be non-square due to parser misalignment (e.g., 70x71)
    # L_matrix from BEA is always square (71x71)
    if A.shape[0] != A.shape[1]:
        # Make A square by using intersection of rows and columns
        common = sorted(set(A.index) & set(A.columns))
        A = A.loc[common, common].fillna(0)
    sectors = list(A.index)
    n = len(sectors)

    # hr = labor income coefficients (compensation / total output)
    comp_row = None
    for idx in value_added.index:
        if "V001" in str(idx):
            comp_row = idx
            break
    if comp_row is None:
        comp_row = value_added.index[0]

    # Align compensation and output to A's sectors
    comp = value_added.loc[comp_row]
    comp_aligned = pd.Series(0.0, index=sectors)
    for s in sectors:
        if s in comp.index:
            comp_aligned[s] = comp[s]

    x_aligned = pd.Series(1.0, index=sectors)
    for s in sectors:
        if s in total_output.index and total_output[s] != 0:
            x_aligned[s] = total_output[s]

    hr = (comp_aligned / x_aligned).values  # 1 x n

    # hc = household consumption pattern (PCE / total household income)
    pce_col = None
    for col in final_demand.columns:
        if "F010" in str(col) or "PCE" in str(col).upper():
            pce_col = col
            break

    if pce_col is not None:
        pce_raw = final_demand[pce_col]
        pce_aligned = pd.Series(0.0, index=sectors)
        for s in sectors:
            if s in pce_raw.index:
                pce_aligned[s] = pce_raw[s]
        total_comp = comp_aligned.sum()
        hc = (pce_aligned / total_comp).values if total_comp > 0 else np.zeros(n)
    else:
        hc = np.ones(n) / n
        logger.warning("PCE column not found; using uniform consumption pattern")

    # Build A-bar: (n+1) x (n+1)
    A_bar = np.zeros((n + 1, n + 1))
    A_bar[:n, :n] = A.values
    A_bar[:n, n] = hc       # household consumption column
    A_bar[n, :n] = hr       # labor income row
    A_bar[n, n] = 0          # household self-consumption = 0

    # Labels
    extended_idx = sectors + ["Households"]
    A_bar_df = pd.DataFrame(A_bar, index=extended_idx, columns=extended_idx)

    # Calculate L-bar = (I - A-bar)^(-1)
    L_bar = linalg.inv(np.eye(n + 1) - A_bar)
    L_bar_df = pd.DataFrame(L_bar, index=extended_idx, columns=extended_idx)

    logger.info(f"Closed model: {n+1}x{n+1} (original {n} sectors + households)")
    return A_bar_df, L_bar_df


def type2_multipliers(L_bar: pd.DataFrame) -> pd.Series:
    """Type II output multipliers from closed-model Leontief inverse.

    Column sums of L-bar for the original sectors (excluding household row sum).
    """
    # Exclude the household column from the sum
    original_sectors = L_bar.columns[:-1]  # all except "Households"
    mult = L_bar[original_sectors].sum(axis=0)
    mult.name = "type2_multiplier"
    return mult


def type1_multipliers(L: pd.DataFrame) -> pd.Series:
    """Type I output multipliers (standard open model)."""
    mult = L.sum(axis=0)
    mult.name = "type1_multiplier"
    return mult


def induced_effects(L: pd.DataFrame, L_bar: pd.DataFrame) -> pd.Series:
    """Induced effects = Type II - Type I multipliers.

    These represent the additional output generated by household
    re-spending of wage income.
    """
    t1 = type1_multipliers(L)
    t2 = type2_multipliers(L_bar)
    # Align on common sectors
    common = t1.index.intersection(t2.index)
    induced = t2.reindex(common) - t1.reindex(common)
    induced.name = "induced_effect"
    return induced
